version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./client:/client
      - ./share:/client/src/data
    networks: [app-network]

  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./server:/api
      - ./share:/tmp/share
    networks: [app-network]

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports:
      - 8008:8008
    volumes:
      - ./app:/app
      - ./share:/tmp/share
    networks: [app-network]
networks:
  app-network:
    driver: bridge
